name: continuous

on:
  push:
    branches-ignore:
      - master
      - release/*
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Run './build.cmd BuildDemoPage'
      run: ./build.cmd BuildDemoPage
    - name: Rewrite Base Href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: 'artifacts/site/index.html'
        base_href: '/Fluxor.Extensions.StoreLogger/'
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/develop' }}
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: artifacts/site/wwwroot
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
